### ISSUE TITLE
Question : Home-Assistant integration

### ISSUE THREAD

**Issue by mattlamb99** [sillyfrog/aiopulse2#3]
Is there a home-assistant integration for this v2?
The existing acmeda integration in home assistant appears to be using aiopulse 1.

I'm about to buy new blinds and the pulse2. 
Thanks

**Comment by sillyfrog** [comment]
Yes, see this post here: https://community.home-assistant.io/t/rollease-acmeda-automate-pulse-hub-integration/57460/219?u=sillyfrog
I'm due to make some minor tweaks to that repo as the PR into HA is taking _way_ too long, but that will get you going with this module in HA.

**Comment by mattlamb99** [comment]
Ah great - thank you :)
